#!/usr/bin/python3
"""
Factorize as many numbers as possible into a product of two smaller numbers.
Usage: factors <file>
is a file containing natural numbers to factor.
One number per line
You can assume that all lines will be valid natural numbers\
        greater than 1.
You can assume that there will be no empy line, and no space\
        before and after the valid number
The file will always end with a new line
Output format: n=p*q
one factorization per line
p and q don’t have to be prime numbers
You can work on the numbers of the file in the order of your choice
The program should run without any dependency: You will not be ablei\
        to install anything on the machine we will run your program on
Time limit: The program will be killed after 5 seconds\
        if it has not finish
"""
# library to get arguments


import sys


def is_prime(n):
    if n < 2:
        return False
    for i in range(2, int(n ** 0.5) + 1):
        if n % i == 0:
            return False
    return True


# fn unpack number factorial
def fc():
    # The function fc to search file to convert number and format  n=p*q
    try:
        revfile = sys.argv[1]
        with open(revfile) as f:
            for revnumber in f:
                revnumber = int(revnumber)
                if revnumber == 1:
                    print("1=1*1")
                    continue
                if revnumber % 2 == 0:
                    print("{}={}*{}".format(revnumber, revnumber // 2, 2))
                    continue
                if is_prime(revnumber):
                    print("{}={}*{}".format(revnumber, revnumber, revnumber))
                    continue
                i = 3
                while i < revnumber // 2:
                    if revnumber % i == 0:
                        print("{}={}*{}".format(revnumber, revnumber // i, i))
                        break
                    i = i + 2
                if i == (revnumber // 2) + 1:
                    print("{}={}*{}".format(revnumber, revnumber, 1))
    except (IndexError):
        pass


# autostart
fc()
